Mother: Where did you get this thing? Throw it away! Unlucky stuff!
Mother: Do…do you think she came back to find us...
Father: Nonsense, we fed her, clothed her and raised her, so we don't owe her anything! If she wants revenge, she should be looking for the goddamn Warlock...