Mr. Li: Holy shit! What did you do!?
NanNan: M-Mr. Li, it was an accident...
Mr. Li: This is so fucking annoying... Whatever, just clean this up quickly, I’ll go get you the key... For fuck's sake...
NanNan: I have to find a way to get the sticker off of the door.