Mr. Li: Bastards like you deserve to die!!
Mr. Li: Xiaoying... are you there? I’ve finally avenged you...
Mr. Li: Forgive me for taking so long to find out...
Xiaoying: I can finally go in peace. Thank you, NanNan. #xiaoyingFade
NanNan: She took the necklace, too.
NanNan: I’m so tired... I want to go home...
Mr. Li: NanNan, go home and don’t say a word to your family. I’ll take care of the mess.