Mother: Will all of this really work...
Father: At least we have to try. Can you stand being gossiped everytime we go out? Aunt Li next door prances around our door with her two grandchildren every day to show off, and the Wang family looks down their noses at us all the time. Some even said that you...
Mother: Stop! I was just afraid that your mother would find out when she came back and start a fight with us.
Father: Let her make trouble! How is her crap worth anything? Burning it wouldn’t change anything. I still think Warlock is more helpful. Everyone believes it, it wouldn’t go wrong...
Mother: Shhh! Keep it quiet, we don’t want the children to hear it...
